### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by davelab6** [hafontia/Natan#2]
The summary at the top of https://github.com/hafontia/PortSansHebrew/ is `ver 1` but should be something like, 

> Hebrew font family

**Comment by hafontia-zz** [comment]
done

**Comment by davelab6** [comment]
Its not quite done, 

<img width="633" alt="screen shot 2016-02-29 at 10 26 43" src="https://cloud.githubusercontent.com/assets/261579/13398982/f73d2c6e-dece-11e5-8c68-98ebcbb0b4b5.png">
