### ISSUE TITLE
Ccedillacomb.cap issue

### ISSUE THREAD

**Issue by davelab6** [hafontia/Natan#6]
A few cap diacritics have issues

<img width="657" alt="screen shot 2016-02-29 at 14 51 36" src="https://cloud.githubusercontent.com/assets/261579/13407190/1b294b00-def5-11e5-9f2e-f4ecc2edb3a5.png">
<img width="495" alt="screen shot 2016-02-29 at 14 51 41" src="https://cloud.githubusercontent.com/assets/261579/13407191/1b292c2e-def5-11e5-9be6-fb3a3cf99d94.png">

**Comment by hafontia-zz** [comment]
fixed! 
![screen shot 2016-03-01 at 10 00 43 pm](https://cloud.githubusercontent.com/assets/13336884/13440102/18551a1c-dff9-11e5-9890-428d88922c5f.png)
